### PR TITLE
Additional vehicle_impact to enable real time field data

### PR DESCRIPTION
**Pull request by Dunge**
Issue #159

### CODE REVIEW

**Comment by Dunge** [comment]
Jacob, in case you are wondering, I'm Pier Castonguay from Ver-Mac

**Review by sknick-iastate — APPROVED** [review]

**Comment by sknick-iastate** [comment]
@Dunge This looks good but I think you need to use the v4.0 release branch (@j-d-b ?).  Then the  v4.0 schema will also need to be updated with the new enumerations.

**Comment by j-d-b** [comment]
> Jacob, in case you are wondering, I'm Pier Castonguay from Ver-Mac

Great, good to know!

>  you need to use the v4.0 release branch

Exactly. The PR needs to target merging your `Dunge:main` branch into `v4.0-release` branch, rather than into `main`. You'll need to merge `v4.0-release` into your `Dunge:main` branch too.

**Review by j-d-b — APPROVED** [review]

**Comment by j-d-b** [comment]
@Dunge thank you for creating this PR!

**Pull request merged**
