### PR TITLE
Update documentation and make editorial changes for the v4.1 release

### PR DESCRIPTION
**Pull request by j-d-b**
This PR proposes changes needed to finalize the v4.1 version of the WZDx specification for official release.

The `fixes/release-v4.1` branch will be updated as necessary fixes are found in reviewing #335. Once review of #335 is complete this PR can be completed and then #335 can be merged, marking the official v4.1 release.

### CODE REVIEW

**Comment by j-d-b** [comment]
The example files FeedInfo version needs to be changed from 4.0 to 4.1

**Comment by sknick-iastate** [comment]
> The example files FeedInfo version needs to be changed from 4.0 to 4.1

I have this updated in all of the examples pull request

**Comment by j-d-b** [comment]
@sknick-iastate understood, thank you, but if our plan is to release v4.1 before merging the examples PR, we need to update it here as well or else the examples will be incorrect (not valid 4.0) until the examples PR is merged.

**Comment by j-d-b** [comment]
I'm leaning toward preferring removing all the TDx references because they're not correct if the object/enum is duplicated in the TDx spec. The references note that the type is "used by" the TDx specification, but since the TDx spec has a copy of the type, the one in this repo/in WZDx isn't used by TDx, they just happen to be the same.

**Comment by j-d-b** [comment]
The schema `$id`s and `$ref`s need to be updated to use the main branch in advance of merging into main

**Comment by j-d-b** [comment]
> The example files FeedInfo version needs to be changed from 4.0 to 4.1

Completed

> The schema $ids and $refs need to be updated to use the main branch in advance of merging into main

Completed

**Comment by j-d-b** [comment]
I reviewed every file with at least a skim except the examples as they will be reviewed and updated in #339.

**Comment by sknick-iastate** [comment]
I went through almost all of the work zone, detour and device spec-content and looks good to me.

**Review by sknick-iastate — APPROVED** [review]

**Review by jlarsonOmahaNE — APPROVED** [review]

**Comment by mark-mockett** [comment]
> I'm leaning toward preferring removing all the TDx references because they're not correct if the object/enum is duplicated in the TDx spec. The references note that the type is "used by" the TDx specification, but since the TDx spec has a copy of the type, the one in this repo/in WZDx isn't used by TDx, they just happen to be the same.
> 
> I think the references should only stay if the types are not duplicated in TDx and if TDx just includes links to WZDx rather than containing copies.

Removed all references to TDx from 'used by' sections

**Pull request merged**
