### PR TITLE
Update RestrictionType.md

### PR DESCRIPTION
**Pull request by imcurtis**
Added draft closure types for discussion

### CODE REVIEW

**Comment by j-d-b** [comment]
Hi @imcurtis, thank you for contributing. Can you [create an issue](https://github.com/usdot-jpo-ode/wzdx/issues/new) to propose this idea for discussion. PRs should be backed by an issue with discussion for tracability.

Thank you.

**Comment by DeraldDudley** [comment]
Thanks Jacob.  I've enlisted the help of a BTS fellow and was teaching him about the WZDx github site.  We'll create and issue for discussion..  Would you like us to drop/delete this?

**Comment by j-d-b** [comment]
@DeraldDudley this PR can remain open, I will convert it to a draft for now until the implementation is discussed in the issue. If you could tag the issue here once created, that would be great, thanks!

**Comment by DeraldDudley** [comment]
Will do.  Thanks.

**Comment by j-d-b** [comment]
See #256.

**Comment by DeraldDudley** [comment]
Hay Jacob,  I'm creating an issue that proposes adding a closure value to the EventType Enumeration.  Do you want to close this and open a new PR or just edit this PR?  Thanks, D

**Comment by j-d-b** [comment]
@DeraldDudley will the new issue replace the implementation proposed here? If so, we can close this PR.

**Comment by DeraldDudley** [comment]
Closing this.  A new implementation strategy can be found in [Issue 270](https://github.com/usdot-jpo-ode/wzdx/issues/270)

**Pull request closed without merging**
