### PR TITLE
Change traffic sensor traffic data properties from Integer to Number value type

### PR DESCRIPTION
**Pull request by dxpack**
Fix for IS #219

### CODE REVIEW

**Comment by j-d-b** [comment]
@dxpack are you able to update this PR so that `average_occupancy` and `volume_vph` on the TrafficSensor and TrafficSensorLaneData also have type `Number`, for consistency?

**Comment by dxpack** [comment]
Will do! Stand by.

**Comment by dxpack** [comment]
Looks like average_occupancy was renamed at some point to occupancy_percent, so I updated that to a number value.

**Comment by j-d-b** [comment]
Fantastic, thank you—the changes looks good. This will be merged for the v4.1 release this summer.

**Review by j-d-b — APPROVED** [review]

**Comment by dxpack** [comment]
No problem - will get to it shortly. Thanks!

**Comment by dxpack** [comment]
Replaced this PR with PR #329 
Refactored changes to apply to schemas/4.1/SwzDeviceFeed.json

Closing this PR

**Comment by dxpack** [comment]
Apologies for any mess here - voting is occurring on this PR, but I was unable to get git to cooperate and give me access to the 4.1 schema as requested, therefore had to create a new PR #329 to update the 4.1 schema. Changes are otherwise identical.

**Pull request closed without merging**
