### PR TITLE
Restore deleted sign_method image

### PR DESCRIPTION
**Pull request by mtfurlan**
This image is still used by
spec-content/enumerated-types/LocationMethod.md

It was deleted in 42b98fcdd837e897ae3e208780c45ce61f7fc12a, and I'm
assuming this was a mistake because it's still referenced.

### CODE REVIEW

**Review by mark-mockett — APPROVED** [review]
thanks @mtfurlan - deletion was an error. hoping another previous maintainer can approve and merge this for posterity.

**Review by j-d-b — APPROVED** [review]
Thanks!

**Comment by sknick-iastate** [comment]
I think the image was removed/renamed as part of the example images clean up.  A similar image below already exists and has the naming convention we were using for the[ example scenarios ](https://github.com/usdot-jpo-ode/wzdx/tree/main/examples#work-zone-feed-examples)(as well as potential future examples referenced in the [discussion](https://github.com/usdot-jpo-ode/wzdx/discussions/131)).

[https://github.com/usdot-jpo-ode/wzdx/blob/main/images/complex_work_zone_with_ramp.png](https://github.com/usdot-jpo-ode/wzdx/blob/main/images/complex_work_zone_with_ramp.png )

There are some differences in the the previous image also included the begin/end location reference based on where the signs were placed.  I'm good with just adding the image back but wanted to give some context in why it was potentially removed.

**Comment by mtfurlan** [comment]
I'm fine modifying https://github.com/usdot-jpo-ode/wzdx/blob/main/spec-content/enumerated-types/LocationMethod.md to use that image, the broken link gets fixed either way.
Let me know if you want me to change it.

**Comment by j-d-b** [comment]
I think having the separate image file for the `sign-method` location method is consistent with that there are specific images for the other location method options, so I support merging this PR.

**Review by sknick-iastate — APPROVED** [review]

**Comment by sknick-iastate** [comment]
That sounds good to me.  Thanks!

**Pull request merged**
